name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
  tags:
   - '*'
   
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Expose version name
      uses: michpohl/android-expose-version-name-action@v1.0.0
      with:
        expose-version-name: 'true'
        expose-version-code: 'true'
      
    - name: Create release and upload apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.ANDROID_VERSION_NAME }}"
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: "SearchApp_Build${{ env.ANDROID_VERSION_NAME }}.apk"
        asset_content_type: application/zip
    


