name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
    
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      env:
          GHR_COMPRESS: xz
          GHR_PATH: app/build/outputs/apk/debug/app-debug.apk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


